### ISSUE TITLE
excited states (TDA) from QChem

### ISSUE THREAD

**Issue by BalticPinguin** [cclib/cclib#974] opened 2020-11-10 14:40 UTC
Dear all, 
I am not sure if it is a matter of version or due to some options; but the `qchemparser` is not able to read-in my coefficients from a TDA-calculations: it expects the form (copy from the source-file)
```` 
    S(  1) --> V(  1) amplitude = -0.3105 alpha
    D( 34) --> S(  1) amplitude =  0.9322 beta
````
While I have
````
    D(    3) --> S(    1) amplitude =  0.9977 beta
````
i.e. there are four spaces between the `(` and `)` while only three are expected; so the indices used to identify the different elements don't match anymore.

I can try to prepare a pull request but wanted first to discuss the strategy used for fixing it: my idea would be to work with regex instead of indices to find the elements; but you probably avoid this with a good reason?

Kind regards,
Hubert

**Comment by shivupa** [comment] 2020-11-10 16:01
Thanks @BalticPinguin 
What version of QChem was this, and do you have a log file we can use as a regression test? 

As to the regex, I tend to avoid them when possible since they are harder to read, but in this case it makes more sense to use one. @berquist might have more thoughts.

**Comment by BalticPinguin** [comment] 2020-11-10 16:27
It is version 5.3.1 (sorry, I forgot to write it right away).
The file I have as a sample is this one: 

[trip.txt](https://github.com/cclib/cclib/files/5518671/trip.txt)

**Comment by langner** [comment] 2020-11-23 17:14
I believe this now fixed. Please reopen if not.

**Closed by langner** 2020-11-23 17:14 UTC
Labels: QChem, bug
