### ISSUE TITLE
Failed to read ORCA output file in QMForge

### ISSUE THREAD

**Issue by glideht** [cclib/cclib#253] opened 2016-03-29 06:48 UTC
I did geometry optimization using ORCA and tried to open the output file using QMForge for Mulliken population analysis. But, I had an error message:

```
Traceback (most recent call last):
File "qmforge.py", line 211, in open
File "/opt/local/Library/Frameworks/Python.framework/Versions/Current/lib/python2.7/site-packages/cclib/parser/logfileparser.py", line 247, in parse
File "/opt/local/Library/Frameworks/Python.framework/Versions/Current/lib/python2.7/site-packages/cclib/parser/orcaparser.py", line 294, in extract
AssertionError
```

I directly contacted with Adam, who made QMForge, and he said this is because "one of the "Geometry convergence" blocks (14th step) is missing the "Energy change" line which is only supposed to happen for the very first step and anytime there is a relaxed optimization scan". I looked at the output file again and also found a message under "ORCA GEOMETRY RELAXATION STEP":

```
Validating the new internal coordinates .... (new redundants).... angle reaching linearity!  179.0802
done

          !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
          !   SERIOUS PROBLEM WITH INTERNALS - ANGLE IS APPROACHING 180 OR 0 DEGREES   !
          !                       REBUILDING A NEW SET OF INTERNALS                    !
          !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

I place the output file in the public domain for further testing. The file is too big to upload here and thus I gave it, which is called CuI-MePY2-CH3CN_optxes.out, to Adam Tenderholt

**Comment by langner** [comment] 2016-04-01 04:07
What is the compressed size? I think we already have comparable files in there. That is the reason it's a separate directory, I guess. It will take a bit to parse, though.

GitLFS is fine as well. Or place it in a separate repo somewhere and test it over HTTP or something. Anything that will let us test it will be good.

**Comment by langner** [comment] 2016-04-11 03:49
@ATenderholt: go ahead and add it to cclib-data and I'll try to fix it for the 1.4 release.

**Comment by ATenderholt** [comment] 2016-04-11 23:40
Just created a PR for cclib-data: https://github.com/cclib/cclib-data/pull/24. I went ahead and used Git LFS, so make sure you have that installed prior to doing a git pull.

**Comment by langner** [comment] 2016-04-14 07:30
The fix is ready.

However, I took a closer look and I would now prefer to not use Git LFS since it's tied to GitHub's servers. The file is not super huge, so I think we can consume it the normal Git way. If anything, I would consider trimming it to just have the problematic section with the missing energy change in the optimization summary. But I also think it's useful to have a few larger files in the regression suite in case we want to optimize the code in the future.

**Comment by ATenderholt** [comment] 2016-04-19 20:13
I've closed the previous PR that used Git LFS and created https://github.com/cclib/cclib-data/pull/27. @langner, you can create the PR for your fix now.

**Comment by ATenderholt** [comment] 2016-04-19 20:16
And I see that there is already a PR. I've resubmitted the Travis build to make sure it passes.

**Comment by ATenderholt** [comment] 2016-04-19 20:49
Ugh, just realized that https://github.com/cclib/cclib-data/pull/27 was still open prior to resubmitting the Travis build and merging this PR. I've manually verified that the problematic file is now parsed after merging #262 so I'm closing this issue.

**Closed by ATenderholt** 2016-04-19 20:49 UTC
Labels: ORCA, regression
