### ISSUE TITLE
Drop 3.7 and add 3.11 to test suite

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [cclib/cclib#1305] opened 2023-11-14 07:19 UTC
A few suggestions:
1. Drop Python 3.7 from the test suite and no longer explicitly support it since it's at EOL
2. Add support for Python 3.11 to the test suite (and 3.12 if it happens to work...)
3. Add `requires-python`, e.g. `requires-python = ">=3.8, <3.12"` to the `setup.py` (plus the corresponding classifiers) to clearly mark what versions are supported by cclib

**Comment by berquist** [comment] 2023-11-15 06:38
This is a duplicate of https://github.com/shivupa/cclib-ci/issues/17 but is also related to #1180.

**Closed by berquist** 2023-11-15 06:38 UTC
Labels: maintenance

**Comment by berquist** [comment] 2024-01-22 01:23
3.7 dropped in #1309.  3.11 added in #1346.  We have a 3.12 image but it's incredibly slow to run the test suite in.

**Comment by Andrew-S-Rosen** [comment] 2024-01-22 01:27
@berquist: I was actually just going to ask you about this. In my `quacc` package, my Python 3.12 runs 2x slower than <=3.11. Part of that seems to be [linked to cclib](https://github.com/Quantum-Accelerators/quacc/actions/runs/7599549144/job/20696707146#step:5:63), although it's definitely not excluded to cclib. 

Do you have an idea why your 3.12 image is so slow to run the test suite? I wonder if it is at all related to https://github.com/python/cpython/issues/109049.
