### ISSUE TITLE
test suite in v1.3 fails with python 2.7

### ISSUE THREAD

**Issue by nonamedotc** [cclib/cclib#160] opened 2015-01-06 02:58 UTC
I am trying to run the test suite with python 2.7 and python 3 as part of packaging for Fedora. It seems that the test suite fails consistently with py2.7 but no problems in python3.

```bash
# python testall.py 
Traceback (most recent call last):
  File "testall.py", line 19, in <module>
    from cclib.parser import (ADF, GAMESS, GAMESSUK, Gaussian,
  File "/usr/lib/python2.7/site-packages/cclib/__init__.py", line 13, in <module>
    from . import parser
  File "/usr/lib/python2.7/site-packages/cclib/parser/__init__.py", line 16, in <module>
    from .adfparser import ADF
  File "/usr/lib/python2.7/site-packages/cclib/parser/adfparser.py", line 17, in <module>
    from . import logfileparser
  File "/usr/lib/python2.7/site-packages/cclib/parser/logfileparser.py", line 35, in <module>
    from .data import ccData
  File "/usr/lib/python2.7/site-packages/cclib/parser/data.py", line 50
SyntaxError: Non-ASCII character '\xc3' in file /usr/lib/python2.7/site-packages/cclib/parser/data.py on line 51, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

```bash
# python3 testall.py

[ ... ]

**** Jaguar8.3/dvb_scan.out: Customized relaxed potential energy surface scan unittest ****
testindices (testScan.JaguarScanTest)
Do the indices match the results from geovalues. ... ok
testnumindices (testScan.JaguarScanTest)
Do the number of indices match number of scan points. ... ok

----------------------------------------------------------------------
Ran 2 tests in 0.000s

OK

********* SUMMARY PER PACKAGE ****************
               Total	Passed	Failed	Errors	Skipped
ADF2007.01       56	 55	  0	  0	  1
ADF2013.01       56	 55	  0	  0	  1
Firefly8.0       73	 72	  0	  0	  1
GAMESS-UK7.0     62	 62	  0	  0	  0
GAMESS-UK8.0    112	112	  0	  0	  0
GAMESS-US2012    80	 79	  0	  0	  1
Gaussian03       99	 97	  0	  0	  2
Gaussian09       97	 95	  0	  0	  2
Jaguar7.0        59	 49	  0	  0	 10
Jaguar8.3       128	113	  0	  0	 15
Molpro2006       68	 63	  0	  0	  5
Molpro2012       68	 64	  0	  0	  4
NWChem6.0        98	 97	  0	  0	  1
ORCA2.9          61	 58	  0	  0	  3
ORCA3.0          59	 57	  0	  0	  2
Psi3             21	 17	  0	  0	  4
Psi4             73	 68	  0	  0	  5
QChem4.2         75	 70	  0	  0	  5

********* SUMMARY OF EVERYTHING **************
TOTAL: 1345	PASSED: 1283	FAILED: 0	ERRORS: 0	SKIPPED: 62

*** Visual tests ***
MO energies of optimised dvb
       ADF2013.01  Firefly8.0  GAMESS-US   Gaussian09  Jaguar8.0   Molpro2012  NWChem6.0   ORCA3.0     QChem4.2    
HOMO   -3.3278     -6.2532     -4.1661     -4.1655     -4.1658     -4.0735     -4.1633     -4.0638     -4.1633
LUMO   +0.1490     +5.7933     +1.3578     +1.0183     +1.0193     +1.1619     +1.0207     +1.1182     +1.0068
H-L     3.4768     12.0465      5.5239      5.1838      5.1851      5.2355      5.1839      5.1820      5.1702
```

Is this expected/intentional? Thanks.

**Comment by berquist** [comment] 2015-01-11 00:39
@langner or @ATenderholt, would adding

```
# -*- coding: utf-8 -*-
```

to the headers of all *.py files solve this? I don't get this problem using Python 2 on any of my computers (OS X, Ubuntu, Arch, and RHEL).

**Comment by langner** [comment] 2015-01-11 15:54
I'm away. I'll take look at this on Tuesday.

**Comment by langner** [comment] 2015-01-16 13:41
@nonamedotc: I think @berquist is probably correct. We'll try to get a fix for this soon and release a minor version soon with other fixes that have accrued since 1.3

**Comment by nonamedotc** [comment] 2015-01-17 00:20
@langner Thank you very much. I will wait for the same. Much appreciated!

**Comment by langner** [comment] 2015-01-21 21:59
I took a look at this, and it's not apparent what the cause is since `data.py` does have the encoding declared at the top and it did go into 1.3. So in principle it should work and it does in fact on a Red Hat box I just tested on.

@nonamedotc: could you provide some specifics about your setup?

**Comment by nonamedotc** [comment] 2015-01-22 01:47
@langner My setup was Fedora rawhide.

This is the complete build log if it helps - https://kojipkgs.fedoraproject.org//work/tasks/6155/8586155/build.log

The list of packages installed when building the package is https://kojipkgs.fedoraproject.org//work/tasks/6155/8586155/root.log

Is there anything I can try from here? python3 works without any issues.

**Comment by langner** [comment] 2015-01-22 02:35
OK! The error in that log is different than what you posted above:
```python
Traceback (most recent call last):
  File "testall.py", line 19, in <module>
    from cclib.parser import (ADF, GAMESS, GAMESSUK, Gaussian,
  File "/builddir/build/BUILD/cclib-1.3/build/lib/cclib/__init__.py", line 33, in <module>
    from . import method
  File "/builddir/build/BUILD/cclib-1.3/build/lib/cclib/method/__init__.py", line 16, in <module>
    from .lpa import LPA
  File "/builddir/build/BUILD/cclib-1.3/build/lib/cclib/method/lpa.py", line 11
SyntaxError: Non-ASCII character '\xc3' in file /builddir/build/BUILD/cclib-1.3/build/lib/cclib/method/lpa.py on line 11, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

This I can reproduce, and will be easy to fix.

**Comment by langner** [comment] 2015-01-22 05:09
@nonamedotc: I believe this will now be fixed. Could you try the latest master?
(https://github.com/cclib/cclib/archive/master.zip)

**Comment by nonamedotc** [comment] 2015-01-23 01:27
Yup! It's most certainly fixed. Thanks for the quick response.

**Comment by langner** [comment] 2015-02-13 23:36
@nonamedotc: FYI cclib 1.3.1 is now released, which includes this fix.

**Closed by langner** 2015-02-13 23:36 UTC
Labels: tests

**Comment by nonamedotc** [comment] 2015-02-14 18:43
Thanks you!
