### ISSUE TITLE
Increase coverage for DALTON

### ISSUE THREAD

**Issue by langner** [cclib/cclib#167] opened 2015-01-22 20:29 UTC
Thanks to @cstein we have a DALTON parser:
https://github.com/cclib/cclib/tree/dalton

We will keep this branch separate until after 1.3.1, and aim to release 1.4 with the new parser after that.

**Comment by cstein** [comment] 2015-01-22 21:02
@langner it looks like it fails the regression testing and that is because the cclib-data hasn't been merged - if you merge that pull-request, it should work. :+1:

**Comment by langner** [comment] 2015-01-24 01:39
> @langner it looks like it fails the regression testing and that is because the cclib-data hasn't been merged - if you merge that pull-request, it should work. :+1:

Indeed. I hesitated with that merge a bit, because I wanted to make sure it wouldn't break the regression pipeline for master. There is a warning, but that's fine until the merge.

**Comment by langner** [comment] 2016-04-11 02:29
We now have decent coverage for DALTON, so I consider this fixed.

**Closed** 2016-04-11 02:29 UTC
Labels: DALTON, parsers
