### ISSUE TITLE
Input incorrectly listed in basicGAMESS-US2012

### ISSUE THREAD

**Issue by gaursagar** [cclib/cclib#416] opened 2017-08-14 08:43 UTC
https://github.com/cclib/cclib/blob/e7cc329adcdcf1347c686b826cab37bf07dd0a0e/data/GAMESS/basicGAMESS-US2012/Trp_polar_tdhf.out#L16

File has actually been computed using the 2014 version. Relevant because US2012 version is to be moved to regressions with https://github.com/cclib/cclib/pull/412.

**Comment by berquist** [comment] 2017-08-14 11:49
This is my doing; I didn't have 2012 on my desktop at the time. I can rerun with 2012 if needed.

**Comment by berquist** [comment] 2017-08-14 14:36
Moving it to cclib-data is fine, but because it's an old version. It isn't a regression, it's a unit test: https://github.com/cclib/cclib/pull/412#discussion_r132966427.

**Comment by berquist** [comment] 2017-08-21 12:30
Fixed by https://github.com/cclib/cclib/pull/412.

**Closed by berquist** 2017-08-21 12:30 UTC
Labels: GAMESS
