### ISSUE TITLE
"ValueError: invalid literal for float()" for ORCA 4.0.1.2 logfile

### ISSUE THREAD

**Issue by dudektria** [cclib/cclib#629] opened 2018-10-04 21:18 UTC
Hi everyone,

I may have found a bug in the ORCA parser:

    $ ccget scfenergies atomcoords 4.out
    Attempting to read 4.out
    Traceback (most recent call last):
      File "/usr/local/bin/ccget", line 11, in <module>
        load_entry_point('cclib==1.6', 'console_scripts', 'ccget')()
      File "/usr/local/lib/python2.7/dist-packages/cclib/scripts/ccget.py", line 165, in ccget
        data = ccread(filename, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/cclib/io/ccio.py", line 175, in ccread
        return log.parse()
      File "/usr/local/lib/python2.7/dist-packages/cclib/parser/logfileparser.py", line 318, in parse
        self.extract(inputfile, line)
      File "/usr/local/lib/python2.7/dist-packages/cclib/parser/orcaparser.py", line 628, in extract
        temp.append(float(vals[k:k+10]))
    ValueError: invalid literal for float(): 1 74.46258

The only place in the output file where the string "1 74.46258" appears is:

    ------------------
    MOLECULAR ORBITALS
    ------------------
                          0         1         2         3         4         5
                     -101.65359 -101.64676 -101.64160 -19.22880 -19.19334 -10.29501
                       2.00000   2.00000   2.00000   2.00000   2.00000   2.00000
                      --------  --------  --------  --------  --------  --------
      0Pd  1s         0.000024 -0.000025 -0.000024 -0.000010  0.000004 -0.000016
    (...)
      4C   2dx2y2    -0.005845  0.030497  0.003297  0.012404 -0.015548 -0.039709
      4C   2dxy      -0.002457 -0.027637 -0.010772 -0.024476  0.017044  0.039060
      4C   6s        29.895635100.086670-23.048342-79.143850-155.230721 74.462587
      4C   4pz        9.010492 14.676334  0.370009 -1.961820-11.737009  8.031800
    (...)

(Last column, second line from bottom to top. I know this is a very strange coefficient, but it's one ORCA actually generated.)

**Comment by langner** [comment] 2018-10-05 04:49
Thanks for the report, Felipe. Looks like an easy fix. Would you be comfortable with sharing the logfile causing this problem, so that we can use it as a regression?

**Comment by dudektria** [comment] 2018-10-08 20:51
Sorry for the late reply. The particular logfile above I would rather not share (right now), sorry.

Luckily, I found [another logfile](https://github.com/cclib/cclib/files/2457832/invalid-literal-for-float.zip) that I could happily share. It gives the same error:

    % ccget scfenergies atomcoords substrate.out                                                               
    Attempting to read opt+freq/substrate-DNP/2w/substrate.out
    Traceback (most recent call last):
      File "/usr/local/bin/ccget", line 11, in <module>
        load_entry_point('cclib==1.6', 'console_scripts', 'ccget')()
      File "/usr/local/lib/python2.7/dist-packages/cclib/scripts/ccget.py", line 165, in ccget
        data = ccread(filename, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/cclib/io/ccio.py", line 175, in ccread
        return log.parse()
      File "/usr/local/lib/python2.7/dist-packages/cclib/parser/logfileparser.py", line 318, in parse
        self.extract(inputfile, line)
      File "/usr/local/lib/python2.7/dist-packages/cclib/parser/orcaparser.py", line 628, in extract
        temp.append(float(vals[k:k+10]))
    ValueError: invalid literal for float(): 2-12.67880

And the error happens in the same session in the output:

    (...)
     17C   2dxy       0.009477  0.001890 -0.001509 -0.002483 -0.005674  0.011353
     17C   6s       -111.755842-12.678807-17.072968  9.959508 99.292696-28.873752
     17C   4pz       24.985500 13.860866  8.898535  3.619561  1.288352 -2.874780
     17C   4px       -1.121219  7.542552  5.004858  3.946401 22.019074 -7.042058
     17C   4py        7.999967  8.284609  5.684538  3.319315  9.953301 -3.972240
    (...)

The file is [attached here](https://github.com/cclib/cclib/files/2457832/invalid-literal-for-float.zip).

**Comment by langner** [comment] 2018-10-10 14:17
OK, maybe it's not such an easy fix, because the formatting in the output used by ORCA there is really messed up. It's not fixed width and extra spaces are not ever added. So, from you same file:
```
 12C   6s       -11.608845-53.775398161.302640-76.633779 29.914985 22.083999
```
... so you can't be certain where the second float ends and the third begins. I suppose we can assume there are always six meaningful digits, but that's also not ideal.

In addition, the current parse throws away everything after column 16, and if the first coefficient is >10 in absolute value, stuff gets cut off (in the example above, -11 become +11!

I'll see what can be done about this.

**Comment by langner** [comment] 2018-10-10 15:20
First of all, thanks for the donation! The fix is in #630 and I added the regression data in cclib/cclib-data#92.

**Comment by dudektria** [comment] 2018-10-10 19:27
Thank you for accepting the suggestion! If you don't mind, I will contact the developers of ORCA about how those coefficients are handled/printed. They may (or may not!) want to change this behaviour in the future.

**Comment by berquist** [comment] 2018-10-13 16:36
Ok, are we good now?

**Comment by langner** [comment] 2018-10-13 17:19
I think so according to tests at least. @dudektria please re-open or create another issue if something's still wrong. To get the fix, you'll need to use the latest master in GitHub for now.

**Closed** 2018-10-15 02:02 UTC
Labels: ORCA

**Comment by dudektria** [comment] 2018-10-25 13:05
(Late) thanks for the fix!

(Just an update on this.) The ORCA team [answered my post on their forum](https://orcaforum.cec.mpg.de/viewtopic.php?f=10&t=4276). An "interface with full accuracy" is planed in the future. I thought you might want to know.

**Comment by langner** [comment] 2018-10-25 15:47
Thanks for the update, Felipe. Looking forward to it!
