### ISSUE TITLE
Bug in gaussian parsing polarizability

### ISSUE THREAD

**Issue by oliver-s-lee** [cclib/cclib#1083] opened 2021-11-30 12:30 UTC
In my .log file the gaussian parser chokes trying to parse polarizabilities:

```
Attempting to read foo.log
[Gaussian foo.log ERROR] Encountered error when parsing.
[Gaussian foo.log ERROR] Last line read:   Exact polarizability:  -20751.174      -0.389    1217.309   -6307.929       0.037    -646.713

Traceback (most recent call last):
  File "/home/oliver/.local/bin/ccget", line 8, in <module>
    sys.exit(ccget())
  File "/home/oliver/.local/lib/python3.8/site-packages/cclib/scripts/ccget.py", line 176, in ccget
    data = ccread(filename, **kwargs)
  File "/home/oliver/.local/lib/python3.8/site-packages/cclib/io/ccio.py", line 169, in ccread
    return log.parse()
  File "/home/oliver/.local/lib/python3.8/site-packages/cclib/parser/logfileparser.py", line 315, in parse
    self.extract(inputfile, line)
  File "/home/oliver/.local/lib/python3.8/site-packages/cclib/parser/gaussianparser.py", line 2110, in extract
    polarizability[indices] = [utils.float(x) for x in
  File "/home/oliver/.local/lib/python3.8/site-packages/cclib/parser/gaussianparser.py", line 2110, in <listcomp>
    polarizability[indices] = [utils.float(x) for x in
  File "/home/oliver/.local/lib/python3.8/site-packages/cclib/parser/utils.py", line 74, in float
    return _BUILTIN_FLOAT(number.replace("D", "E"))
ValueError: could not convert string to float: '.309   -'
```

This happens because the parsing is based on exact line positions, which does not apply in this case at least:
```
polarizability[indices] = [utils.float(x) for x in
                                           [line[23:31], line[31:39], line[39:47], line[47:55], line[55:63], line[63:71]]]
```
It can presumably be fixed by using line.split() or similar instead. I can submit a PR but not the .log file sadly as it is private.

**Comment by ghutchis** [comment] 2021-11-30 16:35
My guess is that the field widths are a bit off in the parser. But I'd be careful about using `.split()` because most Gaussian output is fixed-width (i.e., at some point you'll hit a case where two numbers don't have a whitespace separator). What version of Gaussian are you using?

**Comment by oliver-s-lee** [comment] 2021-11-30 18:27
Ah ok I see good point. This was Gaussian 16, Revision C.01 which looks like it's more recent than the testdata which is why this hasn't popped up I guess. If you compare the relevant lines you can see the change in field width:

G09 (testdata):
```
  Exact polarizability:  68.238  -6.778 143.010   0.000   0.000  11.343
```
G16 A03 (testdata):
```
  Exact polarizability:  68.238  -6.777 143.018   0.000   0.000  11.343
```

G16 C01 (different molecule sorry):
```
  Exact polarizability:      88.162       0.000     124.414       0.000      -0.000      57.579
```

**Comment by shivupa** [comment] 2021-11-30 18:44
Agreed in light of that, could we do something like this in #1084 
```
try:
     # G16 C01 changes polarizability printing
     # Sample:
     #     Exact polarizability:      88.162       0.000     124.414       0.000      -0.000      57.579
     polarizability[indices] = [utils.float(x) for x in [line[23:35], line[35:47], line[47:59], line[59:71], line[71:83], line[83:95]]] <- check these
except:
    # G16A03 and older
    # Sample:
    #       Exact polarizability:  68.238  -6.777 143.018   0.000   0.000  11.343
    polarizability[indices] = [utils.float(x) for x in [line[23:31], line[31:39], line[39:47], line[47:55], line[55:63], line[63:71]]]
```

I think this would be fine until we can update the tests to the newer gaussian version? or we add a sample molecule as a regression test?

**Comment by ghutchis** [comment] 2021-11-30 19:05
@shivupa - would it be better to `try` the old one by default and use the `except` as the newer version? I'm guessing there are far more files with the older format.

@oliver-s-lee - would you be able to run the testdata file with `C01` for a regression test?

**Comment by shivupa** [comment] 2021-11-30 19:08
@ghutchis 
I was thinking that the older format could possibly work but put nonsense in each of the slices of the line, since the older line is shorter than the new format. If we try the new format first, we would get an out of range error triggering the except.

**Comment by oliver-s-lee** [comment] 2021-12-01 09:13
Is there currently a test for the polarizability values? I have an updated test file but it seems to pass just fine using the current parser. It also doesn't raise an exception during parsing so not sure if a regression test would pick anything up?

**Comment by berquist** [comment] 2021-12-30 22:13
> Is there currently a test for the polarizability values? I have an updated test file but it seems to pass just fine using the current parser. It also doesn't raise an exception during parsing so not sure if a regression test would pick anything up?

Yes, the unit test against reference values is at https://github.com/cclib/cclib/blob/5a88163858f97f7419007e2e152045ae26be7eec/test/data/testPolar.py#L31.

I think the part your example was having problems with was the polarizability that gets printed during a frequency calculation, done for at least Gaussian and Q-Chem, which does *not* have unit tests or regressions for either parser.

**Comment by shivupa** [comment] 2022-01-11 23:52
Closing via #1084.

**Closed by shivupa** 2022-01-11 23:52 UTC
Labels: bug, Gaussian
