### ISSUE TITLE
ccenergies in Gaussian RevB.01 are not available

### ISSUE THREAD

**Issue by NikitaFedik** [cclib/cclib#1010] opened 2021-02-08 05:12 UTC
Dear cclib authors, 

I encountered a problem when parsing CC energies from G16 (RevB.01) output. ccenergies attribute is simply not available. I tried parsing ccenergies with my own outputs and the one recalculated from (https://github.com/cclib/cclib/tree/master/data/Gaussian/basicGaussian16/water_ccsdt.com) 
[water_ccsdt_revB1.log](https://github.com/cclib/cclib/files/5941389/water_ccsdt_revB1.log)

I attached G16 log but here is some relevant part: 

 T5(CCSD)=  0.12081412D-04
 CCSD(T)= -0.75017760422D+02
 Discarding MO integrals.
 Leave Link  913 at Sun Feb  7 21:07:53 2021, MaxMem=  1610612736 cpu:               0.3 elap:               0.1
 (Enter /gaussian16/g16/l601.exe)
 Copying SCF densities to generalized density rwf, IOpCl= 0 IROHF=0.

 **********************************************************************

            Population analysis using the SCF Density.

 **********************************************************************

I believe the problem is in line 902 in gaussianparser.py which searches for "... density" but Revision B1 prints "... Density" instead. 
`if line[12:53] == "Population analysis using the SCF density":`

I know Gaussian changes the case of some keywords from revision to revision, so it might be a good idea to look for keywords in a case-insensitive manner to achieve compatibility between revisions. Would you please have a look at the issue? I believe there is a quick fix for that. 
Thank you!

**Comment by shivupa** [comment] 2021-02-09 21:05
Hi Thanks for reporting this and this does seem like a pretty quick fix. Thanks for taking the time to diagnose this and providing the output. We should be able to address this soon.

**Comment by xFNSx** [comment] 2021-02-10 06:53
Thank you!

**Comment by berquist** [comment] 2023-04-24 02:26
Apologies for not noticing that #1110 was a duplicate of this, but it was fixed in #1111.

**Closed by berquist** 2023-04-24 02:26 UTC
Labels: Gaussian, regression
