### ISSUE TITLE
Linear Molecule Vibrations

### ISSUE THREAD

**Issue by jevandezande** [cclib/cclib#426] opened 2017-08-23 14:18 UTC
Vibrations for linear molecules are not currently parsed correctly for ORCA (and I believe other programs). Furthermore, there are currently tests that check if there are `3*N - 6` modes; in linear molecules this should be `3*N - 5`. I've submitted PR #425 that changes these tests and updates parsing for ORCA. It would probably be a good idea to check if all parsers can correctly deal with linear molecules.

**Comment by berquist** [comment] 2017-08-24 12:56
Here are some examples for carbon dioxide, where `3*3 - 5 = 4`. This is probably a weird case though, because of the degenerate bending mode.

```
Attempting to read dalton_nosym.out
vibfreqs
[  566.25   566.25  1435.22  2535.7 ]
Attempting to read gamess.out
vibfreqs
[  566.24   566.24  1435.22  2535.7 ]
Attempting to read molpro.out
vibfreqs
[  566.08   566.08  1435.12  2534.95]
Attempting to read orca_anfreq.out
vibfreqs
[  566.02  1435.01  2534.72]
Attempting to read orca_numfreq.out
vibfreqs
[  566.34  1434.94  2534.73]
Attempting to read orca_usesym_anfreq.out
vibfreqs
[  566.02  1435.01  2534.72]
Attempting to read psi4_nodf_numerical_nosym.out
vibfreqs
[  566.2497   566.2521  1435.2218  2535.7087]
Attempting to read psi4_nodf_numerical.out
vibfreqs
[  566.2497   566.2521  1435.2218  2535.7087]
Attempting to read qchem.out
vibfreqs
[  566.25   566.25  1435.23  2535.71]
```

**Comment by berquist** [comment] 2017-08-24 13:07
Here are some examples for hydrogen fluoride, where `3*2 - 5 = 1`.

```
Attempting to read dalton_nosym.out
vibfreqs
[ 4474.34]
Attempting to read dalton.out
vibfreqs
[ 4474.34]
Attempting to read gamess.out
vibfreqs
[ 4474.34]
Attempting to read molpro.out
vibfreqs
[ 4474.39]
Attempting to read orca_anfreq.out
vibfreqs
[]
Attempting to read orca_numfreq.out
vibfreqs
[]
Attempting to read orca_usesym_anfreq.out
vibfreqs
[]
Attempting to read psi4_nodf_numerical_nosym.out
vibfreqs
[ 4474.4249]
Attempting to read psi4_nodf_numerical.out
vibfreqs
[ 4474.4249]
Attempting to read qchem.out
vibfreqs
[ 4474.34]
```

**Comment by ATenderholt** [comment] 2017-08-24 16:39
Interesting that ORCA is the odd ball. Is cclib correctly pulling out the values from the ORCA log files? Is that from master or another branch?

**Comment by berquist** [comment] 2017-08-24 17:53
This is from current master. The low modes from ORCA are completely different, and one file is just wrong, but I haven't opened it.

```
Attempting to read /home/eric/development/cclib_berquist/data/Molpro/basicMolpro2012/dvb_ir.out
vibfreqs
[   50.29    83.49   151.89   196.27   272.65   299.59   407.97   423.47
   467.66   493.26   587.69   656.2    673.64   705.43   740.37   809.62
   863.46   893.34   895.94   978.5    978.68  1017.76  1036.24  1072.76
  1108.81  1108.97  1118.69  1127.46  1200.37  1261.    1287.36  1296.5
  1351.67  1402.27  1444.98  1445.18  1511.25  1581.03  1590.3   1640.55
  1690.45  1738.23  1822.3   1822.89  3396.2   3396.93  3436.87  3436.92
  3444.62  3448.11  3466.12  3469.09  3547.48  3547.49]
Attempting to read /home/eric/development/cclib_berquist/data/Molpro/basicMolpro2006/dvb_ir.out
vibfreqs
[   50.28    83.62   151.81   190.88   271.17   299.59   407.86   423.63
   467.76   491.56   585.6    656.21   673.66   705.46   740.44   809.63
   864.02   893.3    895.9    978.51   978.66  1017.74  1036.25  1073.12
  1108.81  1108.97  1115.01  1124.25  1206.12  1262.73  1284.79  1297.25
  1351.31  1401.23  1432.8   1437.02  1515.67  1576.7   1587.05  1640.49
  1691.57  1739.33  1819.66  1820.94  3395.37  3396.12  3435.25  3435.29
  3444.72  3448.17  3464.62  3467.52  3546.79  3546.8 ]
Attempting to read /home/eric/development/cclib_berquist/data/GAMESS-UK/basicGAMESS-UK7.0/dvb_ir.out
vibfreqs
[   51.13    85.67   151.36   177.74   262.78   298.98   405.57   424.53
   467.8    485.06   576.61   655.94   672.77   706.16   732.6    809.91
   861.     895.24   897.12   980.52   981.1   1019.95  1038.53  1072.98
  1099.97  1106.6   1106.95  1108.8   1203.95  1261.69  1282.69  1293.44
  1347.48  1398.28  1420.59  1426.85  1513.51  1565.4   1576.01  1639.93
  1689.    1737.94  1812.94  1813.75  3397.97  3398.8   3432.97  3432.99
  3446.91  3450.41  3466.33  3469.31  3549.16  3549.17]
Attempting to read /home/eric/development/cclib_berquist/data/GAMESS-UK/basicGAMESS-UK8.0/dvb_ir.out
vibfreqs
[   55.6     87.15   151.21   176.2    256.6    299.34   407.3    424.88
   468.12   482.34   576.35   655.95   672.46   705.95   732.74   809.87
   860.42   895.37   897.25   981.2    981.3   1019.67  1038.23  1071.99
  1097.93  1105.68  1105.89  1106.04  1200.82  1260.26  1281.99  1291.85
  1347.34  1396.67  1418.99  1424.33  1511.72  1564.32  1573.93  1639.07
  1688.36  1737.32  1812.18  1812.78  3397.23  3397.95  3432.34  3432.37
  3446.24  3449.75  3465.95  3468.9   3548.31  3548.32]
Attempting to read /home/eric/development/cclib_berquist/data/QChem/basicQChem4.2/dvb_ir.out
vibfreqs
[   47.24    80.8    152.36   178.92   262.67   301.86   408.38   425.37
   470.34   485.6    578.67   659.05   672.02   709.27   735.87   811.22
   861.59   897.07   898.6    981.66   981.78  1020.65  1039.06  1072.6
  1102.69  1108.72  1108.88  1110.63  1203.8   1263.09  1285.19  1295.91
  1350.01  1399.73  1420.63  1426.69  1514.75  1565.29  1574.86  1639.28
  1689.7   1737.77  1815.59  1816.58  3399.68  3400.4   3438.13  3438.17
  3458.77  3462.27  3477.87  3480.8   3552.24  3552.26]
Attempting to read /home/eric/development/cclib_berquist/data/GAMESS/basicGAMESS-US2014/dvb_ir.out
vibfreqs
[   47.87    81.18   152.3    183.71   266.07   300.25   407.11   422.26
   467.26   491.2    580.26   656.61   669.77   705.49   736.57   809.79
   862.58   891.17   894.22   979.89   979.99  1015.16  1033.91  1069.07
  1104.86  1107.61  1107.77  1112.4   1199.63  1256.51  1281.74  1296.04
  1348.24  1395.13  1428.03  1432.07  1510.05  1569.61  1579.35  1636.51
  1689.86  1735.4   1816.76  1817.98  3394.75  3395.47  3433.64  3433.69
  3448.46  3451.95  3471.76  3474.72  3546.78  3546.79]
Attempting to read /home/eric/development/cclib_berquist/data/GAMESS/basicFirefly8.0/dvb_ir.out
vibfreqs
[   38.65    58.28   155.47   197.57   292.15   330.65   444.46   477.2
   526.06   528.44   629.32   738.22   740.26   795.49   797.66   918.56
   945.75  1021.12  1022.94  1145.75  1145.81  1154.61  1163.    1179.47
  1187.82  1213.23  1234.94  1246.73  1246.98  1333.42  1386.8   1418.05
  1428.89  1534.16  1552.6   1565.81  1666.69  1716.22  1724.84  1819.25
  1888.91  1948.25  2038.69  2040.37  3658.18  3659.26  3710.99  3711.08
  3715.56  3722.64  3741.53  3744.84  3816.54  3816.56]
Attempting to read /home/eric/development/cclib_berquist/data/GAMESS/basicGAMESS-US2017/dvb_ir.out
vibfreqs
[   47.87    81.18   152.3    183.71   266.07   300.25   407.11   422.26
   467.26   491.2    580.26   656.61   669.77   705.49   736.57   809.79
   862.58   891.17   894.22   979.89   979.99  1015.16  1033.91  1069.07
  1104.86  1107.61  1107.77  1112.4   1199.63  1256.51  1281.74  1296.04
  1348.24  1395.13  1428.03  1432.07  1510.05  1569.61  1579.35  1636.51
  1689.86  1735.4   1816.76  1817.98  3394.75  3395.47  3433.64  3433.69
  3448.46  3451.95  3471.76  3474.72  3546.78  3546.79]
Attempting to read /home/eric/development/cclib_berquist/data/ORCA/basicORCA2.9/dvb_ir.out
vibfreqs
[  265.36   365.02   367.3    407.94   491.26   578.09   673.06   716.15
   809.33   861.95   948.51   971.58  1007.22  1031.27  1110.17  1165.31
  1177.2   1209.71  1234.22  1245.31  1254.39  1262.15  1275.87  1296.33
  1333.04  1339.27  1353.12  1359.98  1382.07  1387.05  1398.81  1427.71
  1429.37  1443.39  1476.02  1494.78  1508.41  1512.17  1564.13  1602.92
  1682.84  1690.77  1739.04  1813.6   3038.98  3065.59  3077.76  3087.29
  3109.08  3394.89  3432.8   3451.03  3475.79  3546.49]
Attempting to read /home/eric/development/cclib_berquist/data/ORCA/basicORCA3.0/dvb_ir.out
vibfreqs
[  266.19   365.42   367.47   406.98   491.16   578.89   672.87   716.35
   809.01   862.45   948.33   971.4   1007.4   1031.56  1109.78  1165.13
  1177.25  1208.45  1232.41  1245.27  1254.39  1259.87  1274.46  1295.31
  1333.46  1340.6   1352.85  1359.4   1382.39  1386.98  1397.56  1423.98
  1429.6   1441.25  1475.94  1494.51  1506.81  1512.05  1564.14  1601.82
  1681.11  1691.26  1738.49  1812.64  3037.55  3063.86  3076.84  3086.35
  3108.86  3394.56  3431.54  3449.31  3474.57  3546.29]
Attempting to read /home/eric/development/cclib_berquist/data/DALTON/basicDALTON-2013/dvb_ir.out
vibfreqs
[   46.75    79.01   149.56   179.77   264.98   299.9    407.8    423.74
   468.     487.49   578.36   656.69   673.1    706.32   734.89   810.17
   862.22   894.53   895.65   980.04   980.07  1016.88  1035.63  1073.2
  1101.58  1106.87  1106.89  1110.14  1203.64  1260.85  1284.25  1296.27
  1350.17  1398.29  1421.94  1427.23  1514.44  1565.29  1574.93  1639.57
  1690.95  1738.58  1814.87  1815.85  3394.22  3394.93  3432.91  3432.93
  3447.96  3451.45  3471.42  3474.44  3546.67  3546.72]
Attempting to read /home/eric/development/cclib_berquist/data/DALTON/basicDALTON-2015/dvb_ir.out
vibfreqs
[   46.75    79.01   149.56   179.77   264.98   299.9    407.8    423.74
   468.     487.49   578.36   656.69   673.1    706.32   734.89   810.17
   862.22   894.53   895.65   980.04   980.07  1016.88  1035.63  1073.2
  1101.58  1106.87  1106.89  1110.14  1203.64  1260.85  1284.25  1296.27
  1350.17  1398.29  1421.94  1427.23  1514.44  1565.29  1574.93  1639.57
  1690.95  1738.58  1814.87  1815.85  3394.22  3394.93  3432.91  3432.93
  3447.96  3451.45  3471.42  3474.44  3546.67  3546.72]
Attempting to read /home/eric/development/cclib_berquist/data/regression/GAMESS/GAMESS-US2012/dvb_ir.out
vibfreqs
[   47.87    81.04   152.39   183.65   265.34   299.71   407.04   422.27
   467.32   491.18   580.55   656.66   669.77   705.55   736.56   809.82
   862.63   891.58   894.24   979.89   980.02  1015.24  1033.93  1069.07
  1104.85  1107.65  1107.71  1112.36  1199.57  1256.43  1281.76  1296.12
  1348.31  1395.32  1428.03  1432.03  1510.04  1569.57  1579.4   1636.47
  1689.85  1735.46  1816.78  1817.94  3394.99  3395.61  3433.8   3433.9
  3448.57  3452.06  3471.75  3474.77  3546.93  3546.99]
Attempting to read /home/eric/development/cclib_berquist/data/regression/GAMESS/PCGAMESS/dvb_ir.out
vibfreqs
[   38.65    58.28   155.47   197.57   292.15   330.65   444.46   477.2
   526.06   528.44   629.32   738.22   740.26   795.49   797.66   918.56
   945.75  1021.12  1022.94  1145.75  1145.81  1154.61  1163.    1179.47
  1187.82  1213.23  1234.94  1246.73  1246.98  1333.42  1386.8   1418.05
  1428.89  1534.16  1552.6   1565.81  1666.69  1716.22  1724.84  1819.25
  1888.91  1948.25  2038.69  2040.37  3658.18  3659.26  3710.99  3711.08
  3715.56  3722.64  3741.53  3744.84  3816.54  3816.56]
Attempting to read /home/eric/development/cclib_berquist/data/regression/ORCA/ORCA2.9/dvb_ir.out
vibfreqs
[  265.36   365.02   367.3    407.94   491.26   578.09   673.06   716.15
   809.33   861.95   948.51   971.58  1007.22  1031.27  1110.17  1165.31
  1177.2   1209.71  1234.22  1245.31  1254.39  1262.15  1275.87  1296.33
  1333.04  1339.27  1353.12  1359.98  1382.07  1387.05  1398.81  1427.71
  1429.37  1443.39  1476.02  1494.78  1508.41  1512.17  1564.13  1602.92
  1682.84  1690.77  1739.04  1813.6   3038.98  3065.59  3077.76  3087.29
  3109.08  3394.89  3432.8   3451.03  3475.79  3546.49]
Attempting to read /home/eric/development/cclib_berquist/data/regression/ORCA/ORCA2.8/dvb_ir.out
vibfreqs
[ -862.04  -545.35  -324.49  -243.9   -229.21  -192.01  -175.91    -0.
    -0.      -0.      -0.      -0.      -0.      -0.      -0.      -0.
    -0.      -0.      -0.      -0.      -0.      -0.      -0.      -0.
    -0.      -0.      -0.      -0.       0.       0.       0.       0.
     0.       0.       0.       0.       0.       0.       0.       0.
     0.       0.       0.       0.       0.       0.       0.     789.1
   834.31  1233.88  1255.48  1278.47  1687.55  1711.79]
Attempting to read /home/eric/development/cclib_berquist/data/regression/ORCA/ORCA2.6/dvb_ir.out
vibfreqs
[  341.56   356.51   356.98   496.21   549.24   638.82   652.63   680.32
   787.9    853.42   858.58   876.03   936.15  1022.71  1081.98  1163.69
  1183.59  1193.98  1202.36  1219.78  1235.41  1273.8   1277.74  1285.3
  1300.2   1312.6   1313.53  1340.63  1347.89  1350.66  1357.93  1375.26
  1414.37  1414.57  1456.98  1460.05  1596.    1599.46  1653.42  1685.31
  1702.29  1765.26  1775.22  1784.12  3506.95  3525.01  3527.68  3529.01
  3539.72  3548.45  3557.16  3573.91  3656.85  3670.2 ]
Attempting to read /home/eric/development/cclib_berquist/data/regression/Jaguar/Jaguar4.2/dvb_ir.out
vibfreqs
[   72.45   113.26   176.9    183.75   267.59   312.07   407.93   428.75
   476.57   489.46   578.33   662.85   672.74   715.4    736.18   812.47
   862.8    900.31   901.58   983.36   983.46  1022.64  1041.39  1073.59
  1101.69  1108.15  1108.3   1110.35  1204.2   1262.43  1286.26  1297.1
  1357.53  1398.18  1421.6   1426.22  1515.39  1566.18  1575.37  1640.7
  1692.85  1741.03  1815.07  1815.32  3402.3   3403.49  3442.44  3442.94
  3450.94  3454.06  3469.52  3471.79  3553.36  3553.38]
Attempting to read /home/eric/development/cclib_berquist/data/regression/Jaguar/Jaguar6.5/dvb_ir.out
vibfreqs
[   72.45   113.26   176.9    183.75   267.59   312.07   407.93   428.75
   476.57   489.46   578.33   662.85   672.74   715.4    736.18   812.47
   862.8    900.31   901.58   983.36   983.46  1022.64  1041.39  1073.59
  1101.69  1108.15  1108.3   1110.35  1204.2   1262.43  1286.26  1297.1
  1357.53  1398.18  1421.6   1426.22  1515.39  1566.18  1575.37  1640.7
  1692.85  1741.03  1815.07  1815.32  3402.3   3403.49  3442.44  3442.94
  3450.94  3454.06  3469.52  3471.79  3553.36  3553.38]
Attempting to read /home/eric/development/cclib_berquist/data/Gaussian/basicGaussian03/dvb_ir.out
vibfreqs
[   52.7881    83.9368   148.1571   178.6727   262.8396   297.7972
   407.3941   424.4503   467.4912   485.8774   577.9704   656.1725
   673.259    706.4108   734.7939   810.1865   862.6788   895.7477
   897.557    980.231    980.3383  1020.0259  1038.5286  1073.5743  1100.4
  1105.4116  1105.5654  1109.0728  1205.8919  1263.8741  1285.0561
  1296.0506  1351.5509  1399.3807  1419.3438  1425.9357  1515.4286
  1564.9375  1574.6576  1641.3863  1691.5895  1739.8213  1814.1806
  1815.0417  3397.7986  3398.5154  3439.0191  3439.0651  3448.4053
  3451.9232  3468.4     3471.3473  3549.6915  3549.7034]
Attempting to read /home/eric/development/cclib_berquist/data/Gaussian/basicGaussian09/dvb_ir.out
vibfreqs
[   52.7882    83.9373   148.1576   178.6728   262.8397   297.7975
   407.3942   424.4505   467.4915   485.8775   577.9705   656.1727
   673.259    706.4111   734.7939   810.1866   862.6787   895.7477
   897.5569   980.2308   980.3381  1020.0258  1038.5285  1073.5742
  1100.4003  1105.4118  1105.5657  1109.073   1205.8918  1263.874
  1285.0559  1296.0504  1351.5508  1399.3806  1419.3439  1425.9357
  1515.4284  1564.9373  1574.6574  1641.3861  1691.5897  1739.821
  1814.1806  1815.0418  3397.7981  3398.5149  3439.0187  3439.0647
  3448.4052  3451.9231  3468.3998  3471.3471  3549.6914  3549.7032]
Attempting to read /home/eric/development/cclib_berquist/data/Jaguar/basicJaguar7.0/dvb_ir.out
vibfreqs
[   72.45   113.25   176.88   183.76   267.6    312.06   407.94   428.74
   476.56   489.46   578.33   662.84   672.74   715.39   736.18   812.47
   862.8    900.3    901.58   983.36   983.46  1022.64  1041.39  1073.59
  1101.69  1108.14  1108.29  1110.36  1204.2   1262.43  1286.26  1297.11
  1357.52  1398.18  1421.6   1426.22  1515.39  1566.18  1575.37  1640.7
  1692.85  1741.02  1815.07  1815.32  3402.3   3403.49  3442.44  3442.94
  3450.94  3454.06  3469.52  3471.79  3553.37  3553.38]
Attempting to read /home/eric/development/cclib_berquist/data/Jaguar/basicJaguar8.3/dvb_ir.out
vibfreqs
[   53.46    85.47   149.83   179.44   263.51   298.87   407.65   424.37
   468.     486.78   578.54   656.39   673.71   706.5    735.18   810.36
   862.76   895.38   897.42   980.12   980.23  1019.68  1038.22  1073.61
  1101.57  1106.08  1106.24  1109.93  1204.95  1262.91  1284.91  1296.29
  1351.26  1398.64  1420.76  1426.93  1515.02  1565.43  1575.12  1641.37
  1691.4   1740.01  1814.43  1815.31  3396.42  3397.14  3437.91  3437.95
  3446.99  3450.51  3466.82  3469.76  3548.27  3548.28]
```

**Comment by berquist** [comment] 2017-08-24 17:56
Ok, there's nothing wrong with the parser for `data/regression/ORCA/ORCA2.8/dvb_ir.out`. Whoever ran that file wan't paying attention at all, and some I/O problem during the numerical frequency calculation led to an incomplete calculation:

```
WARNING: It seems that the Hessian Matrix ISN'T COMPLETE!
         Please check your results VERY carefully!
         For possible error information check files /home/xaverw/rechnungen/scratch/dvb_ir.last*.dpl*
         If necessary - restart the job with local HessianFiles.
         Modify your input options to ensure convergence and/or
         avoid other sources of problems
```

**Comment by berquist** [comment] 2017-08-24 17:58
I haven't looked at @jevandezande's PR yet, but this is the ORCA output for HF:

```
-----------------------
VIBRATIONAL FREQUENCIES
-----------------------

   0:         0.00 cm**-1
   1:         0.00 cm**-1
   2:         0.00 cm**-1
   3:         0.00 cm**-1
   4:         0.00 cm**-1
   5:      4473.89 cm**-1
```

**Comment by ATenderholt** [comment] 2017-08-24 18:20
I think @jevandezande's PR should fix it, but probably worth having the HF files in regressions. Can you add whatever you have? Or do you think they should be part of the standard unit tests?

**Comment by berquist** [comment] 2017-08-25 00:32
Well, I found a *ton* of bugs and regressions trying to parse files I didn't show here (DALTON 2016 with symmetry, NWChem 6.3, latest Psi4 with analytic Hessian) plus a serious bug in an actual program (Psi4), so I'll add them.

It might be worth making the HF frequency a unit test; it's a single value, and the error between programs should be small.

**Comment by langner** [comment] 2017-08-25 06:02
Great debugging Eric! I agree it'd be nice to have all your examples as regression at the very least. And to fix all the bugs (or at least file them).

I'm OK in principle with adding the HF unit test, but what additional test case or attribute does it really cover beyond the existing DVB example?

**Comment by jevandezande** [comment] 2017-08-25 07:59
My pull release should properly parse any size of linear atom. I just confirmed it with HF. It currently prints out a warning as there is no simple way to check if a molecule is linear.

At the moment the frequencies, modes, IR spectrum, and thermochemistry are all parsed in separate sections. A future PR should probably combine them all to simplify the code. This would also allow confirming that the molecule is linear, because it is printed as such in the thermochemistry section. This would take a little bit of work, as it would also need to include the optional Raman section.

@berquist, I'd recommend submitting an issue in the [psi4](https://github.com/psi4/psi4) repo for the bug you found, they are usually pretty quick about fixing stuff like that.

**Comment by berquist** [comment] 2017-08-25 14:48
Ok, everything looks good now for ORCA wrt CO2 and HF.

I agree that we don't need more unit tests. Everything can be covered by regressions.

**Comment by muammar** [comment] 2019-05-03 18:40
I have been bitten by this, too. Linear molecules are not parsed correctly. Is this going to be fixed for 1.6.2?

**Comment by berquist** [comment] 2019-05-04 00:23
I am not sure why this has been sitting so long, so I'll figure it out now.

**Comment by berquist** [comment] 2019-05-04 00:34
@muammar Can you post an example logfile where you're having trouble? It looks like the problems from this issue have been fixed.

**Comment by langner** [comment] 2019-05-04 04:22
Agreed. Rereading the history it seems all the core issue were addressed in #505, #506 and #507. What remained to be done was to add regression files and test - @berquist do you have these at hand.

Given that, I agree it would be good to see the new example that is failing. @muammar could you donate your file for our regression tests?

**Comment by langner** [comment] 2019-05-06 15:06
Thanks for that, Eric. I assume it was just those two.

@muammar feel free to respond here again with an example that still doesn't work. Otherwise I will close this out when v1.6.2 is released.

**Comment by muammar** [comment] 2019-05-06 16:25
Hi @berquist and @langner. Thanks for your fast reply. This is the output file that creates this problem:


[raw.txt](https://github.com/cclib/cclib/files/3148906/raw.txt)

Let me know if you can reproduce it with this file and if there is something else I can help with.

**Comment by langner** [comment] 2019-05-08 15:22
@muammar have you tried the master branch? Works fine for me:
```
$ ccget -l ~/raw.txt 
Attempting to read /home/kml/raw.txt
cclib can parse the following attributes from /home/kml/raw.txt:
  aonames
  atombasis
  atomcharges
  atomcoords
  atommasses
  atomnos
  charge
  coreelectrons
  enthalpy
  entropy
  freeenergy
  gbasis
  geotargets
  geovalues
  grads
  homos
  metadata
  mocoeffs
  moenergies
  moments
  mult
  natom
  nbasis
  nmo
  optdone
  pressure
  scfenergies
  scftargets
  scfvalues
  temperature
  vibdisps
  vibfreqs
  vibirs
```

We could also roll out a quick release, if you prefer.

**Comment by muammar** [comment] 2019-05-17 03:19
Sorry to get back to you so late. I confirm that using `master` fixes the issue for me.

**Comment by langner** [comment] 2019-05-18 04:28
Thanks for confirming.

**Closed** 2019-05-18 04:28 UTC
Labels: bug, parsers
