### ISSUE TITLE
Cannot parse gaussian IRC log

### ISSUE THREAD

**Issue by bertadenes** [cclib/cclib#360] opened 2017-03-17 12:00 UTC
I encountered an error trying to parse IRC outputs. The structure of the output is slightly different, thus when gaussianparser.py tries to parse the step, (line 822 in the latest version) it fails to cast a string. It is due to the fact that IRC has an additional "Pt X" in the beginning on the line.
Eventually I think it can be just fixed by just adding a couple lines, see the following example.
The same change does work with version 1.4 as well.
[gaussianparser.py.zip](https://github.com/cclib/cclib/files/850454/gaussianparser.py.zip)

**Comment by bertadenes** [comment] 2017-03-17 13:17
[gaussianparser.py.zip](https://github.com/cclib/cclib/files/850635/gaussianparser.py.zip)
This one can handle IRC over 100 points as well.

**Comment by langner** [comment] 2017-03-17 15:51
Hi, would you like to create a pull request, or should we just patch it for you?

Would it be possible for you to also provide us with the logfile to test this?

**Comment by bertadenes** [comment] 2017-03-17 16:49
I could create a pull request with the patched file, but it would require add me in order to create a new branch, wouldn't it?
On the other hand, I cannot give my first problematic output away, I will create another relevant example. Thank you for your understanding.

**Comment by langner** [comment] 2017-05-12 07:43
@bertadenes If you manage to create another relevant example, please reopen this and we can continue. Meanwhile I'll close this since some time has passed. Please let us know if you have any problems or questions.

**Comment by bertadenes** [comment] 2017-05-16 06:33
@langner Sorry, this just slipped through my table lately. Yes, I do have a relevant example which was properly processed by using the modified code I uploaded earlier.
[IRCparse-example.out.zip](https://github.com/cclib/cclib/files/1003390/IRCparse-example.out.zip)

**Comment by langner** [comment] 2017-05-16 16:18
Thanks Denes! I will take a look soon.

**Comment by langner** [comment] 2017-08-23 16:15
The file attached here being added to regressions in cclib/cclib-data#67.

**Closed by langner** 2017-08-23 16:15 UTC
Labels: bug, Gaussian
